apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-x1234
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-x1234
  name: chatbot-x1234
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
